version: '3.8'

services:
  web:
    build:
      context: ./web
    container_name: desafio-web
    ports:
      - "80:4200"
    networks:
      - desafio-network

  api:
    build:
      context: ./api
    container_name: desafio-backend
    volumes:
      - ./api:/var/www
    ports:
      - "8000:80"
    networks:
      - desafio-network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: desafio-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: desafio
      MYSQL_DATABASE: desafio
      MYSQL_USER: desafio
      MYSQL_PASSWORD: desafio
    ports:
      - "3306:3306"
    networks:
      - desafio-network
    volumes:
      - mysql-data:/var/lib/mysql

networks:
  desafio-network:
    driver: bridge

volumes:
  mysql-data: